SET serveroutput ON;
DECLARE
  MEMBER_NAME MEMBERS.MNAME%TYPE := '&name';
  MEMBER_ADDR MEMBERS.MADDRESS%TYPE := '&address';
  MEMBER_TEL TELEPHONE.PHONENUMBER%TYPE := '&telephone';
  MEMBER_TYPE MEMBERS.MTYPE%TYPE := '&type';
  MEMBER_ID MEMBERS.MEMBERID%TYPE;
  MEMBER_FEES MEMBERS.FEESDUE%TYPE;
  MEMBER_PAYMENT MEMBERS.FEESPAID%TYPE;
  FOOTBALL VARCHAR2(3);
  BASKETBALL VARCHAR2(3);
  YOGA VARCHAR2(3);
  TAEKWONDO VARCHAR2(3);
BEGIN
  INSERT_MEMBER(MEMBER_NAME, MEMBER_ADDR, MEMBER_TYPE, MEMBER_TEL);
  MEMBER_ID := GET_MEMBER_ID(MEMBER_NAME, MEMBER_ADDR);
  IF IS_FULLMEMBER(MEMBER_ID) THEN
    FOOTBALL := '&FOOTBALL?';
    BASKETBALL := '&BASKETBALL?';
    YOGA := '&YOGA?';
    TAEKWONDO := '&TAEKWONDO?';
    MEMBER_FEES := MEMBER_ACTIVITIES(MEMBER_ID, FOOTBALL, BASKETBALL, YOGA, TAEKWONDO);
  ELSE
    MEMBER_FEES := 150;
  END IF;
  dbms_output.put_line('Fees due: ' || MEMBER_FEES);
  MEMBER_PAYMENT := '&PAYMENT';
  PROCESS_PAYMENT(MEMBER_ID, MEMBER_PAYMENT, MEMBER_FEES);  
END;

